name: blocbase
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev (for private packages).
publish_to: 'none'  # Remove this line if you want to publish to pub.dev

# Version and build number.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.4.4
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/blocbase_logo.png"  
flutter_native_splash:
  color: "#86A789" 
  image: assets/images/blocbase_logo.png
  android_gravity: center
  fullscreen: true
  android: true
  ios: true 

# Recommended lints for good coding practices.

flutter:
  uses-material-design: true
  assets:
    - assets/images/blocbase_logo.png  # Make sure the logo is included in your assets

# If you want to add custom fonts in the future, you can specify them here.
# Example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
